name: flutter_stories_editor
description: "Flutter stories editor"
version: 0.0.1
homepage: https://github.com:holyboom1/flutter_stories_editor.git

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cross_file: ^0.3.4+1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  advanced_media_picker: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/icons/
    - assets/image/