name: flutter_stories_editor
description: "This plugin allows you to create a story editor and viewer in your Flutter app. Here is a detailed description of its features and functions"
version: 0.0.4
homepage: https://github.com/holyboom1/flutter_stories_editor.git

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cross_file: ^0.3.4+1
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  advanced_media_picker: ^0.0.13
  collection: ^1.18.0
  matrix2d: ^1.0.4

  cached_video_player: ^2.0.4
  visibility_detector: ^0.4.0+2

  path_provider: ^2.1.3
  path: ^1.9.0
  ffmpeg_kit_flutter_min_gpl: ^6.0.3

  transparent_image: ^2.0.1
  video_player: ^2.5.2
  video_thumbnail: ^0.5.3

  palette_generator: ^0.3.3+3

  video_compress: ^3.1.2

  flutter_image_compress: ^2.3.0

  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
    - assets/icons/
    - assets/image/